[package]
name = "aoc_macros"
version = "1.0.0"
edition = "2021"
authors = ["Paddi <secure@cryne.me>"]
license = "AGPL-3-only"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = {  version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
